# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4pKcBr0dW-o1RzII-tdlEGuC61unlOd
"""

import pandas as pd

data={
    "Review": [
        "This product is amazing",
        "I love this service",
        "Very disappointed with the quality",
        "Worst experience ever",
        "Excellent customer support",
        "Not worth the money"
    ],
    "Sentiment": [
        "Positive",
        "Positive",
        "Negative",
        "Negative",
        "Positive",
        "Negative"
    ]
}

df=pd.DataFrame(data)
df

X=df["Review"]
y=df["Sentiment"]

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.feature_extraction.text import CountVectorizer
X_train_vec=CountVectorizer().fit_transform(X_train)
X_test_vec=CountVectorizer().fit_transform(X_test)

from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_vec,y_train)

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

y_pred

y_test

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

new_review=["this product is excellent"]
new_review_vec = vectorizer.transform(new_review)

result = model.predict(new_review_vec)

print("Sentiment:", result[0])